apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  namespace: practica2-201800496 
  labels:
    app: my-deployment
spec:
  selector:
    matchLabels:
      app: my-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: my-deployment
    spec:
      hostname: grpc-pod-host
      containers:
        - name: grpc-client-api
          image: solaresjuan98/clientgrpc_go
          env:
          - name: HOST
            value: grpc-pod-host
          ports:
            - containerPort: 5000
        - name: grpc-server
          image: solaresjuan98/servergrpc_node_v3
          ports:
            - containerPort: 50051
          env:
          - name: RABBIT_HOST
            value: rabbitmq.rabbits
            #value: 34.125.249.69
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grpc-deployment
  name: svc-grpc
spec:
  type: LoadBalancer
  selector:
    app: grpc-deployment
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP